const SITE = {
  name: "금동호",
  title: "금동호 | AI 서비스·풀스택 개발자",
  description: "Next.js와 Python 백엔드를 기반으로 AI 기능을 실제 웹·앱 서비스로 구현하는 개발자 금동호의 포트폴리오입니다.",
  githubUsername: "gold3534-tech",
  githubUrl: "https://github.com/gold3534-tech",
};

const PROJECTS = [
  {
    slug: "semoduck",
    title: "세모덕",
    summary: "팬덤별 커뮤니티 활동과 굿즈 탐색, 유저 거래 기능을 제공하는 웹 플랫폼",
    description: "커뮤니티를 중심에 두고 굿즈 탐색과 유저 거래를 자연스럽게 연결하는 팬덤 플랫폼입니다.",
    category: ["풀스택"],
    role: "프론트엔드와 서비스 흐름 구현",
    techStack: ["Next.js App Router", "TypeScript", "Supabase", "PostgreSQL", "Tailwind CSS", "Vercel"],
    thumbnail: "/public/projects/semoduck/cover.png",
    screenshots: [
      {
        src: "/public/projects/semoduck/home.png",
        alt: "세모덕 홈 대시보드 화면",
      },
      {
        src: "/public/projects/semoduck/gallery.png",
        alt: "세모덕 팬덤 갤러리 목록 화면",
      },
      {
        src: "/public/projects/semoduck/gallery-detail.png",
        alt: "세모덕 갤러리 상세와 AI 인기 키워드 화면",
      },
      {
        src: "/public/projects/semoduck/search.png",
        alt: "세모덕 굿즈 검색 화면",
      },
      {
        src: "/public/projects/semoduck/product-detail.png",
        alt: "세모덕 굿즈 상세와 외부 구매 링크 화면",
      },
      {
        src: "/public/projects/semoduck/market.png",
        alt: "세모덕 유저거래 게시판 화면",
      },
      {
        src: "/public/projects/semoduck/market-detail.png",
        alt: "세모덕 유저거래 상세 화면",
      },
      {
        src: "/public/projects/semoduck/mobile-mockup.png",
        alt: "세모덕 모바일 앱 확장 목업 화면",
      },
    ],
    githubUrl: "https://github.com/gold3534-tech/semoduck",
    overview: "관심사별 갤러리, 게시글, 굿즈 검색, 내부 거래 게시판을 하나의 사용자 흐름으로 묶은 프로젝트입니다.",
    background: "팬덤 활동은 이야기, 상품 정보, 거래가 따로 흩어져 있어 사용자가 여러 화면을 오가야 합니다. 세모덕은 이 흐름을 한 서비스 안에서 이어지도록 설계했습니다.",
    flow: "사용자 인증 → 갤러리 탐색 → 게시글과 댓글 → 굿즈 검색 → 찜 또는 유저 거래 게시글 확인",
    features: ["인증과 사용자 세션", "게시글과 댓글", "좋아요와 북마크", "이미지 업로드", "작성자·관리자 권한", "굿즈 탐색과 찜", "유저 거래", "신고와 관리자 기능"],
    troubleshooting: [
      {
        problem: "인증 상태에 따라 작성, 수정, 신고 기능의 접근 조건이 달라졌습니다.",
        cause: "화면 단위 조건 처리와 서버 데이터 권한 기준이 분리되어 있었습니다.",
        solution: "사용자 세션, 작성자 여부, 관리자 여부를 기능별 조건으로 나누고 버튼 노출과 요청 흐름을 함께 정리했습니다.",
        learned: "권한은 UI 숨김만으로 끝나지 않고 데이터 요청 기준까지 같은 흐름으로 다뤄야 한다는 점을 확인했습니다.",
      },
    ],
    learned: "커뮤니티, 상품, 거래처럼 성격이 다른 기능도 사용자 목표를 기준으로 묶으면 더 자연스러운 서비스 흐름을 만들 수 있었습니다.",
  },
  {
    slug: "nadeurism",
    title: "나들이즘 (Nadeurism)",
    summary: "여행 스타일과 지역, 테마, 예산 조건에 맞춰 여행지를 추천하고 지도에 모아보는 출시 모바일 앱",
    description: "원스토어에 출시한 맞춤형 여행지 추천 앱으로, 소셜 로그인부터 조건 기반 추천, 여행 준비 목록, 지도 확인, 프로필 흐름까지 모바일 앱 경험으로 연결했습니다.",
    category: ["모바일", "풀스택"],
    role: "모바일 화면 구현, Google·Kakao 로그인, 추천 API 연동, 여행 준비/지도 화면 구성",
    techStack: ["Flutter", "Dart", "FastAPI", "Python", "REST API", "Kakao Map API", "Google OAuth", "Kakao Login", "One Store"],
    thumbnail: "/public/projects/nadeurism/cover.png",
    screenshots: [
      {
        src: "/public/projects/nadeurism/login.png",
        alt: "나들이즘 Google 및 Kakao 로그인 화면",
      },
      {
        src: "/public/projects/nadeurism/home.png",
        alt: "나들이즘 홈 화면과 축제 목록",
      },
      {
        src: "/public/projects/nadeurism/region-select.jpg",
        alt: "나들이즘 지역 선택 화면",
      },
      {
        src: "/public/projects/nadeurism/preference-select.jpg",
        alt: "나들이즘 테마와 예산 선택 화면",
      },
      {
        src: "/public/projects/nadeurism/recommend-result.jpg",
        alt: "나들이즘 추천 여행지 결과 화면",
      },
      {
        src: "/public/projects/nadeurism/map.jpg",
        alt: "나들이즘 선택한 여행지 지도 화면",
      },
      {
        src: "/public/projects/nadeurism/empty-plan.jpg",
        alt: "나들이즘 여행 준비 시작 화면",
      },
      {
        src: "/public/projects/nadeurism/profile.jpg",
        alt: "나들이즘 마이 프로필 화면",
      },
    ],
    liveUrl: "https://m.onestore.co.kr/v2/ko-kr/app/0001002339",
    liveLabel: "앱스토어",
    overview: "나들이즘은 사용자의 지역, 테마, 예산 조건에 맞춰 여행지를 추천하고 선택한 장소를 지도에서 확인할 수 있는 모바일 앱입니다. 원스토어 공개 설명처럼 여행 스타일에 맞는 맞춤 일정 추천 경험을 목표로, 로그인 이후 홈, 여행 준비, 추천 결과, 지도, 마이 프로필 흐름을 구성했습니다.",
    background: "여행지를 고를 때 사용자는 지역, 취향, 예산, 동선 정보를 여러 서비스에서 따로 확인해야 합니다. 나들이즘은 조건 선택과 추천 결과, 지도 확인을 한 앱 안에 묶어 여행 준비 과정을 가볍게 시작할 수 있도록 설계했습니다.",
    flow: "Google·Kakao 로그인 → 홈과 축제 정보 확인 → 여행 준비 시작 → 지역 선택 → 테마·예산 선택 → 추천 여행지 조회 → 선택한 장소 지도 확인 → 마이 프로필에서 여행 기록 확인",
    features: ["Google·Kakao 소셜 로그인", "지역별 여행지 탐색", "테마와 예산 기반 추천 조건 입력", "맞춤형 추천 여행지 결과", "선택 여행지 지도 표시", "여행 준비 목록", "축제 정보 노출", "마이 프로필과 여행 통계", "원스토어 앱 등록"],
    troubleshooting: [
      {
        problem: "소셜 로그인 이후 앱 화면과 추천 API 요청 흐름이 자연스럽게 이어져야 했습니다.",
        cause: "Google과 Kakao 로그인은 인증 결과, 토큰 전달, 사용자 상태 저장 방식이 달라 화면 진입 조건이 흔들릴 수 있었습니다.",
        solution: "로그인 완료 지점부터 홈 화면 진입, 사용자 정보 표시, 추천 API 호출까지의 상태를 나누어 확인하고 실패 시 다시 시도할 수 있는 흐름으로 정리했습니다.",
        learned: "모바일 앱에서는 로그인 성공 자체보다 이후 화면과 API 요청이 끊기지 않는 경험이 더 중요했습니다.",
      },
      {
        problem: "추천 결과를 단순 목록으로만 보여주면 사용자가 여행 동선을 이해하기 어려웠습니다.",
        cause: "장소 추천과 지도 확인이 분리되면 선택한 여행지가 어느 지역에 있는지 다시 확인해야 했습니다.",
        solution: "추천 결과에서 선택된 장소 수를 관리하고 지도 화면에 번호 마커로 표시해 목록과 위치 정보를 연결했습니다.",
        learned: "여행 앱의 추천 기능은 결과 정확도뿐 아니라 사용자가 바로 이동 계획으로 이해할 수 있는 시각화가 필요했습니다.",
      },
    ],
    learned: "출시 앱을 만들면서 인증, 추천 API, 지도, 앱스토어 배포까지 사용자가 실제로 설치해 쓰는 모바일 서비스 흐름을 경험했습니다.",
  },
  {
    slug: "jobnawa",
    title: "JOBNAWA",
    summary: "원티드, 랠릿, 점핏 채용 공고를 통합해 기술 스택·지역·연봉 인사이트를 제공하는 Streamlit 팀 프로젝트",
    description: "여러 IT 채용 플랫폼의 공고 데이터를 수집하고 정제해 개발자가 조건에 맞는 공고와 시장 트렌드를 한 화면에서 비교할 수 있게 만든 채용 정보 큐레이션 대시보드입니다.",
    category: ["데이터", "풀스택"],
    role: "팀 프로젝트 참여, 채용 데이터 수집·정제와 Streamlit 분석 화면 구현",
    techStack: ["Python", "Streamlit", "Selenium", "BeautifulSoup4", "Pandas", "NumPy", "Regex", "Matplotlib", "Plotly", "Folium"],
    thumbnail: "/public/projects/jobnawa/main.png",
    screenshots: [
      {
        src: "/public/projects/jobnawa/main.png",
        alt: "JOBNAWA 채용 공고 검색과 분석 대시보드 화면",
      },
      {
        src: "/public/projects/jobnawa/features.jpeg",
        alt: "관련 기술 스택 추천, 채용 공고 분포 지도, 연봉 상승률 보고서 기능 요약 이미지",
      },
      {
        src: "/public/projects/jobnawa/logo.png",
        alt: "JOBNAWA 서비스 로고 이미지",
      },
    ],
    githubUrl: "https://github.com/gold3534-tech/jobnawa-portfolio",
    overview: "JOBNAWA는 원티드, 랠릿, 점핏처럼 흩어져 있는 IT 채용 공고를 한곳에서 검색하고 비교하는 데이터 기반 큐레이션 서비스입니다. 사용자는 회사명, 공고명, 지역, 기술 스택, 경력, 마감 조건으로 공고를 필터링하고 현재 시장에서 함께 요구되는 기술 스택과 지역별 채용 밀도를 확인할 수 있습니다.",
    background: "개발자 채용 공고는 플랫폼마다 흩어져 있고, 같은 직무라도 요구 기술과 연봉 흐름을 한눈에 비교하기 어렵습니다. 다나와처럼 조건을 좁혀 비교하는 경험을 채용 공고에 적용하고, 수집된 데이터를 분석 자료로 바꾸는 것을 목표로 했습니다.",
    flow: "채용 사이트 URL 수집 → Selenium·BeautifulSoup 기반 공고 크롤링 → 주소·기술 스택·경력 데이터 정규화 → CSV 통합 데이터 생성 → Streamlit 필터 UI → 채용 카드, 워드클라우드, 지도, 연봉·스택 분석 시각화",
    features: ["회사명·공고명 키워드 검색", "지역·기술 스택·경력·마감일 필터링", "공고 카드형 목록과 페이지네이션", "기술 스택 WordCloud 트렌드 분석", "연관 기술 스택 추천", "지역별 채용 공고 분포 지도", "직무별 연봉 상승률 리포트", "여러 채용 사이트 데이터 통합"],
    troubleshooting: [
      {
        problem: "채용 사이트마다 동적 로딩 방식과 렌더링 속도가 달라 크롤링 중 일부 데이터가 누락될 수 있었습니다.",
        cause: "페이지가 완전히 로딩되기 전에 HTML을 수집하거나, 스크롤 이후 나타나는 공고를 충분히 기다리지 못하는 문제가 있었습니다.",
        solution: "WebDriverWait와 스크롤 자동화 로직을 적용해 주요 요소가 로드된 뒤 데이터를 수집하도록 바꾸고, 이미지 로딩 차단과 브라우저 주기적 초기화로 크롤링 부담을 줄였습니다.",
        learned: "크롤링은 선택자만 맞추는 작업이 아니라 페이지 로딩 타이밍과 브라우저 리소스 관리까지 함께 다뤄야 안정적이었습니다.",
      },
      {
        problem: "사이트마다 주소 표기와 기술 스택 표기 방식이 달라 지도 시각화와 필터 결과가 흔들렸습니다.",
        cause: "같은 지역이나 기술도 서로 다른 문자열로 저장되면 필터링과 좌표 매핑에서 같은 값으로 묶이지 않았습니다.",
        solution: "정규표현식과 전처리 규칙으로 주소, 경력, 기술 스택 데이터를 표준화하고 통합 CSV를 기준으로 분석 화면을 구성했습니다.",
        learned: "데이터 서비스의 품질은 화려한 차트보다 먼저 원천 데이터의 표준화와 일관성에서 결정된다는 점을 체감했습니다.",
      },
    ],
    learned: "크롤러, 데이터 정제, 분석 모듈, Streamlit UI를 함께 연결하면서 수집한 데이터를 사용자가 탐색할 수 있는 대시보드 경험으로 바꾸는 흐름을 익혔습니다.",
  },
  {
    slug: "ax-orchestration",
    title: "AX Orchestration Platform",
    summary: "AI Agent, Task, Tool의 실행 흐름을 시각적으로 구성하고 확인하는 오케스트레이션 인터페이스",
    description: "복잡한 AI 실행 흐름을 노드와 그래프 기반 UI로 구성하고 실행 상태를 확인하는 플랫폼입니다.",
    category: ["프론트엔드", "AI"],
    role: "워크플로 UI와 실행 상태 시각화",
    techStack: ["React", "TypeScript", "React Flow", "WebSocket", "REST API"],
    thumbnail: "/public/projects/ax-orchestration/cover.png",
    screenshots: [
      {
        src: "/public/projects/ax-orchestration/home-runner.png",
        alt: "AX Orchestration Platform 실행 입력 화면",
      },
      {
        src: "/public/projects/ax-orchestration/flow-builder.png",
        alt: "AX Orchestration Platform Home 2D 실행 시각화 화면",
      },
      {
        src: "/public/projects/ax-orchestration/crew-builder.png",
        alt: "AX Orchestration Platform Agent 생성 탭 화면",
      },
      {
        src: "/public/projects/ax-orchestration/run-launcher.png",
        alt: "AX Orchestration Platform Task 생성 탭 화면",
      },
      {
        src: "/public/projects/ax-orchestration/agents-library.png",
        alt: "AX Orchestration Platform Flow 생성 탭 화면",
      },
      {
        src: "/public/projects/ax-orchestration/tasks-library.png",
        alt: "AX Orchestration Platform Crew 생성 탭 화면",
      },
    ],
    githubUrl: "https://github.com/gold3534-tech/AX_Orchestration_platform",
    overview: "사용자는 Agent와 Task를 만들고, 실행 단위를 그래프로 연결한 뒤, 실행 과정과 결과를 시각적으로 확인할 수 있습니다.",
    background: "AI Agent 실행은 내부 단계가 많아 사용자가 현재 어떤 작업이 진행 중인지 이해하기 어렵습니다. 이를 노드와 실행 상태 중심의 화면으로 풀었습니다.",
    flow: "Agent·Task 생성 → Crew 그래프 구성 → Flow 그래프 구성 → 실행 → 이벤트와 결과 확인",
    features: ["Agent·Task·Tool 노드 UI", "드래그 기반 워크플로 구성", "실행 상태 시각화", "실시간 실행 결과 반영", "복잡한 AI 실행 흐름을 이해 가능한 UI로 표현"],
    troubleshooting: [
      {
        problem: "그래프 편집 상태와 실행 상태가 한 화면에서 섞여 사용자가 현재 맥락을 파악하기 어려웠습니다.",
        cause: "생성, 검증, 실행, 결과 확인 단계를 같은 시각 언어로 표현하고 있었습니다.",
        solution: "노드 편집 영역과 실행 상태 피드백을 분리하고 단계별 상태를 카드와 연결선으로 구분했습니다.",
        learned: "AI 워크플로 UI는 멋진 그래프보다 사용자가 다음 행동을 이해하는 구조가 더 중요했습니다.",
      },
    ],
    learned: "React Flow 기반 인터페이스에서 도메인 모델과 화면 상태를 분리하면 복잡한 실행 흐름도 안정적으로 표현할 수 있습니다.",
  },
  {
    slug: "card-rag",
    title: "AI 카드 추천 RAG 시스템",
    summary: "사용자 질문을 분석해 적절한 카드를 검색하고 추천하는 RAG 기반 서비스",
    description: "카드 혜택 데이터를 문서화하고 하이브리드 검색과 LLM 답변을 연결한 추천 서비스입니다.",
    category: ["AI", "데이터"],
    role: "RAG 문서 구성, 검색 흐름, 추천 이유 생성",
    techStack: ["Python", "OpenAI API", "LangChain", "ChromaDB", "BM25", "Vector Search", "Streamlit"],
    thumbnail: "/public/projects/card-rag/cover.png",
    screenshots: ["/public/projects/card-rag/cover.png"],
    githubUrl: "https://github.com/gold3534-tech/ai-card-recommendation-rag",
    overview: "사용자의 소비 패턴과 질문을 분석해 관련 카드 후보를 검색하고, 추천 이유를 함께 생성하는 RAG 서비스입니다.",
    background: "카드 상품은 혜택 조건이 복잡해 사용자가 자신에게 맞는 카드를 직접 비교하기 어렵습니다. 검색과 생성형 AI를 결합해 납득 가능한 추천 흐름을 만들었습니다.",
    flow: "사용자 질문 → 소비 조건 추출 → Vector Search와 BM25 검색 → 조건 필터링 → LLM 추천 이유 생성",
    features: ["문서 임베딩", "벡터 검색", "키워드 검색", "하이브리드 검색", "추천 이유 생성", "검색 결과와 LLM 답변 연결"],
    troubleshooting: [
      {
        problem: "벡터 검색만으로는 특정 혜택 키워드가 포함된 카드를 놓치는 경우가 있었습니다.",
        cause: "사용자 질문의 의미 유사도와 카드 혜택의 정확한 키워드 매칭이 항상 같은 방향으로 작동하지 않았습니다.",
        solution: "Vector Search와 BM25를 함께 사용하고 검색 결과를 결합해 후보를 구성했습니다.",
        learned: "RAG 추천은 임베딩 검색만 믿기보다 데이터 성격에 맞는 검색 방식을 조합하는 것이 안정적입니다.",
      },
    ],
    learned: "정형 데이터를 문서와 metadata로 나누어 설계하면 검색 품질과 추천 설명을 함께 개선할 수 있습니다.",
  },
  {
    slug: "resume-interview-agent",
    title: "AI Interview Agent",
    summary: "이력서 PDF를 분석해 기술 면접 질문과 최종 평가를 생성하는 FastAPI 웹앱",
    description: "PDF 이력서에서 핵심 키워드를 추출하고 LLM 기반 기술 면접 흐름을 제공하는 AI 면접 서비스입니다.",
    category: ["AI", "풀스택"],
    role: "FastAPI 백엔드, 면접 흐름, Slack 알림 연동",
    techStack: ["Python", "FastAPI", "LangChain", "Anthropic Claude", "Slack API", "JavaScript"],
    thumbnail: "/public/projects/resume-interview-agent/cover.png",
    screenshots: ["/public/projects/resume-interview-agent/cover.png"],
    githubUrl: "https://github.com/gold3534-tech/resume-interview-agent",
    overview: "지원자의 이력서 PDF를 업로드하면 텍스트를 추출하고, 핵심 기술 키워드에 맞춘 면접 질문과 후속 질문, 최종 평가를 생성합니다.",
    background: "기술 면접은 지원자의 실제 경험과 기술 키워드에 맞춰 질문이 달라져야 합니다. 이력서 분석부터 질문 생성, 평가 알림까지 하나의 흐름으로 묶었습니다.",
    flow: "PDF 업로드 → 텍스트 추출 → 핵심 키워드 분석 → 면접 질문 생성 → 답변 기반 후속 질문 → 최종 평가와 Slack 알림",
    features: ["PDF 이력서 업로드", "텍스트와 핵심 기술 키워드 추출", "기술 면접 질문 생성", "후속 질문 진행", "PASS/FAIL 평가 구조화", "Slack 평가 완료 알림", "API 오류 시 demo fallback"],
    troubleshooting: [
      {
        problem: "외부 LLM 또는 문서 파싱 API 호출이 실패하면 면접 화면 흐름이 끊길 수 있었습니다.",
        cause: "실제 API 응답에만 의존하면 데모와 테스트 환경에서 안정적인 화면 확인이 어렵습니다.",
        solution: "DEMO_FALLBACK 옵션을 두고 API 실패 시에도 임시 질문과 평가 결과로 흐름을 계속 확인할 수 있게 구성했습니다.",
        learned: "AI 서비스는 모델 응답뿐 아니라 실패 시 사용자가 어디까지 진행할 수 있는지도 서비스 품질에 포함됩니다.",
      },
    ],
    learned: "문서 분석, LLM 질문 생성, 웹 UI, 외부 알림 API를 연결하면서 AI 기능을 실제 업무 흐름에 붙이는 구조를 경험했습니다.",
  },
  {
    slug: "portfolio-website",
    title: "Portfolio Website",
    summary: "금동호의 프로젝트와 기술 스택을 정리한 정적 포트폴리오 웹사이트",
    description: "HTML, CSS, JavaScript 기반으로 프로젝트 데이터와 다중 페이지 라우트를 구성한 포트폴리오 사이트입니다.",
    category: ["프론트엔드"],
    role: "사이트 구조, 반응형 UI, 프로젝트 데이터 구성",
    techStack: ["HTML", "CSS", "JavaScript", "GitHub Pages", "Responsive UI"],
    thumbnail: "",
    screenshots: [],
    githubUrl: "https://github.com/gold3534-tech/portfolio_website",
    overview: "프로젝트 목록, 상세 페이지, 기술 스택, 소개, GitHub 정보를 하나의 정적 사이트 안에서 탐색할 수 있도록 구성했습니다.",
    background: "단순 원페이지보다 실제 라우트와 상세 페이지가 있는 포트폴리오가 프로젝트 흐름을 더 명확하게 보여줄 수 있습니다.",
    flow: "공통 프로젝트 데이터 → 목록 카드 렌더링 → 상세 라우트 렌더링 → GitHub 공개 API 정보 표시",
    features: ["다중 페이지 정적 라우트", "프로젝트 필터", "프로젝트 상세 페이지", "반응형 헤더와 모바일 메뉴", "GitHub API fallback UI", "SEO 파일 구성"],
    troubleshooting: [
      {
        problem: "기존 정적 사이트는 원페이지와 모달 중심이라 새로고침 가능한 상세 경로가 없었습니다.",
        cause: "프로젝트 데이터를 화면 내부에서 직접 다루고 실제 파일 기반 라우트가 분리되어 있지 않았습니다.",
        solution: "공통 데이터 파일과 폴더 기반 index.html 라우트를 만들고 같은 렌더링 스크립트를 공유하도록 바꿨습니다.",
        learned: "정적 사이트에서도 파일 구조와 데이터 분리를 잘 잡으면 포트폴리오 규모 확장이 가능합니다.",
      },
    ],
    learned: "프레임워크 없이도 접근 가능한 경로, 반응형 UI, 데이터 분리를 갖춘 포트폴리오 구조를 만들 수 있었습니다.",
  },
  {
    slug: "traffic-accident",
    title: "서울시 교통사고 위험 예측 지도",
    summary: "서울시 교통사고·기상·교통량 데이터를 학습해 자치구별 사고 위험도를 지도에 시각화한 예측 시스템",
    description: "LightGBM 모델과 Flask 웹 인터페이스를 연결해 사용자 입력 조건과 실시간 기상·교통량 기반 위험도를 비교할 수 있는 데이터 프로젝트입니다.",
    category: ["데이터"],
    role: "데이터 수집·전처리, LightGBM 모델 학습, Flask 기반 예측 화면 구현",
    techStack: ["Python", "Pandas", "LightGBM", "SMOTE", "Flask", "JavaScript", "기상청 API", "TOPIS API", "Choropleth Map"],
    thumbnail: "/public/projects/traffic-accident/BIN0005.png",
    screenshots: [
      {
        src: "/public/projects/traffic-accident/BIN0004.png",
        alt: "교통사고 위험예측지도 예측 방식 선택 화면",
      },
      {
        src: "/public/projects/traffic-accident/BIN0002.png",
        alt: "사용자 입력 조건 기반 서울시 자치구별 교통사고 위험도 지도",
      },
      {
        src: "/public/projects/traffic-accident/BIN0005.png",
        alt: "실시간 기상 정보 기반 서울시 자치구별 교통사고 위험도 지도",
      },
      {
        src: "/public/projects/traffic-accident/BIN0001.png",
        alt: "오프라인 학습 단계와 온라인 예측 단계로 구성된 시스템 구조도",
      },
    ],
    overview: "2021년부터 2023년까지의 서울시 교통사고 데이터에 기온, 강수량, 적설량, 교통량, 지역 통계 데이터를 결합해 자치구별 사고 발생 확률을 예측했습니다. 결과는 서울시 행정구역 단위의 Choropleth 지도에 색상 농도로 표시해 고위험 지역을 빠르게 파악할 수 있게 구성했습니다.",
    background: "기존 사고 다발 지역 분석은 과거 통계 중심이라 실시간 기상 변화와 교통량 변화를 반영하기 어렵습니다. 이 프로젝트는 정적인 사고 통계에 기상청 초단기실황 API와 서울시 TOPIS 교통량 데이터를 결합해 현재 조건에서의 동적인 위험도 변화를 보여주는 것을 목표로 했습니다.",
    flow: "TAAS·TMACS·기상청·서울시 열린데이터 수집 → 자치구·시간대·요일 단위 전처리 → 결측치 보완과 SMOTE 적용 → LightGBM 이진 분류 모델 학습 → Flask API 연결 → 사용자 입력 또는 실시간 데이터 기반 예측 → 서울시 위험도 지도 시각화",
    features: ["2021~2023년 교통사고·기상·교통량 데이터 결합", "자치구·시간대·요일 기반 분석 단위 설계", "SMOTE를 활용한 사고 발생 클래스 불균형 보정", "LightGBM 기반 사고 발생 확률 예측", "사용자 입력 조건 기반 위험도 예측", "기상청·TOPIS API 기반 실시간 위험도 예측", "서울시 자치구 Choropleth 지도 시각화", "Spearman ρ, RMSE, Jaccard 등 예측 결과 비교"],
    troubleshooting: [
      {
        problem: "교통사고가 발생하지 않은 샘플이 많아 모델이 사고 미발생 쪽으로 치우칠 가능성이 있었습니다.",
        cause: "자치구, 시간대, 요일 조합 단위로 데이터를 만들면 실제 사고 발생 클래스보다 미발생 클래스가 훨씬 많아집니다.",
        solution: "사고 발생 여부를 이진 분류 문제로 정의하고 SMOTE를 적용해 사고 발생 클래스의 학습 비중을 보정했습니다.",
        learned: "위험 예측 모델은 전체 정확도만 높이는 것보다 실제 사고 가능성을 놓치지 않도록 데이터 분포를 먼저 다루는 과정이 중요했습니다.",
      },
      {
        problem: "사용자 입력 기반 예측과 실시간 데이터 기반 예측 결과를 단순히 화면만으로 비교하기 어려웠습니다.",
        cause: "두 예측은 같은 모델을 사용하지만 입력 조건이 달라 지역별 위험 순위와 확률 차이를 정량적으로 확인할 필요가 있었습니다.",
        solution: "Spearman 순위상관계수, RMSE, Bias, Jaccard Index, Elasticity를 함께 계산해 공간적 위험 순위와 예측값 차이를 비교했습니다.",
        learned: "지도 기반 결과는 시각화와 함께 순위·오차·고위험군 일치도를 같이 제시해야 예측 결과의 의미가 분명해졌습니다.",
      },
    ],
    learned: "데이터 수집과 전처리, 모델 학습, API, 지도 화면이 하나로 이어져야 예측 결과가 사용자가 판단할 수 있는 서비스 형태로 전달된다는 점을 경험했습니다.",
  },
];

const SKILL_GROUPS = [
  {
    title: "Frontend",
    skills: [
      ["Next.js", "세모덕에서 App Router 기반 화면, 인증 흐름, 서비스 구조 구현"],
      ["React", "AX Orchestration Platform에서 그래프 기반 인터페이스 구현"],
      ["TypeScript", "프로젝트 데이터와 UI 상태를 명확한 타입 기준으로 관리"],
      ["JavaScript", "정적 화면과 API 연동, 지도 시각화 인터랙션 구현"],
      ["Tailwind CSS", "반응형 화면과 재사용 가능한 스타일 시스템 구성"],
      ["React Flow", "Agent와 Task의 워크플로 노드 UI 구성"],
      ["Flutter", "나들이즘 모바일 화면과 앱 흐름 구현"],
      ["Dart", "모바일 앱 상태와 API 요청 흐름 구현"],
    ],
  },
  {
    title: "Backend",
    skills: [
      ["Python", "AI, 데이터, API 서버 프로젝트의 기본 언어로 사용"],
      ["FastAPI", "나들이즘과 AI 프로젝트의 REST API 서버 구현"],
      ["Flask", "교통사고 예측 API와 데이터 서비스 실험에 사용"],
      ["REST API", "프론트엔드와 백엔드 사이의 요청·응답 흐름 설계"],
      ["Supabase", "세모덕 인증, 세션, PostgreSQL 기반 데이터 저장에 사용"],
      ["PostgreSQL", "사용자, 게시글, 권한 등 관계형 데이터 구조 설계"],
      ["MySQL", "교육 과정과 데이터 프로젝트에서 기본 질의와 모델링 학습"],
    ],
  },
  {
    title: "AI & Data",
    skills: [
      ["OpenAI API", "추천 이유 생성과 생성형 AI 응답 흐름 구현"],
      ["LangChain", "RAG 검색 결과와 LLM 응답을 연결하는 체인 구성"],
      ["RAG", "카드 추천 프로젝트에서 검색 기반 답변 흐름 구현"],
      ["AI Agent", "AX 프로젝트에서 Agent 실행 흐름을 시각화"],
      ["ChromaDB", "카드 혜택 document embedding 저장과 검색에 사용"],
      ["BM25", "키워드 검색을 Vector Search와 결합"],
      ["Scikit-learn", "데이터 분석과 모델 비교 과정에서 사용"],
      ["LightGBM", "교통사고 위험 예측 모델에 적용"],
      ["Pandas", "공공데이터와 카드 혜택 데이터 전처리에 사용"],
    ],
  },
  {
    title: "Deploy & Tools",
    skills: [
      ["Git", "브랜치와 변경 이력을 기준으로 프로젝트 작업 관리"],
      ["GitHub", "프로젝트 코드, README, 스크린샷을 정리해 공개"],
      ["Vercel", "Next.js 기반 프로젝트 배포에 사용"],
      ["Linux VPS", "모바일 앱 백엔드 서버 배포와 운영 환경 구성"],
      ["Docker", "교육 과정과 실험 프로젝트에서 실행 환경 격리 경험"],
      ["Swagger", "FastAPI 문서로 요청 형식과 응답을 확인"],
      ["Postman", "API 요청, 인증 헤더, 오류 응답 점검에 사용"],
    ],
  },
];
